name: Bug Report
description: File a bug report
labels: bug
body:
  - type: checkboxes
    id: unique
    attributes:
      label: Make sure you are not opening a duplicate.
      options:
        - label: "[I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Are you using the latest version of the app? If not, try updating to see if it resolves your issue. You can [find the latest versions here](https://github.com/sindresorhus/caprine/releases)."
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: On which OS are you using Caprine?
      multiple: true
      options:
      - Windows
      - Linux
      - macOS
  - type: input
    id: version-caprine
    attributes:
      label: Caprine version.
      placeholder: ex. 2.54.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: ex. I can't see emojis.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information.
      description: Any more information you would like to add? If you have any screenshots, videos, or other information that you feel is necessary to explain the issue, feel free to attach them here.
      placeholder: If you are running Linux please tell us what Desktop Environment you are using on which distribution.
